"""add indexes

Revision ID: 31bce740cf99
Revises: 6a49dfec089d
Create Date: 2025-12-20 16:47:14.884376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bce740cf99'
down_revision: Union[str, None] = '6a49dfec089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_budgets_user_category_month', 'budgets', ['user_id', 'category_id', 'month'], unique=False)
    op.create_index('ix_transactions_occurred_at', 'transactions', ['occurred_at'], unique=False)
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index('ix_wallets_user_id', 'wallets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallets_user_id', table_name='wallets')
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.drop_index('ix_transactions_occurred_at', table_name='transactions')
    op.drop_index('ix_budgets_user_category_month', table_name='budgets')
    # ### end Alembic commands ###
