"""add user_profiles table

Revision ID: 88cdc83bc37e
Revises: 4c7d40ae0679
Create Date: 2025-12-22 22:47:19.226434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cdc83bc37e'
down_revision: Union[str, None] = '4c7d40ae0679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_nutrient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('saturated_fat_g', sa.Float(), nullable=False),
    sa.Column('monounsaturated_fat_g', sa.Float(), nullable=False),
    sa.Column('polyunsaturated_fat_g', sa.Float(), nullable=False),
    sa.Column('omega_3_g', sa.Float(), nullable=False),
    sa.Column('omega_6_g', sa.Float(), nullable=False),
    sa.Column('vitamin_a_mcg', sa.Float(), nullable=False),
    sa.Column('vitamin_b1_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_b2_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_b3_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_b5_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_b6_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_b9_folate_mcg', sa.Float(), nullable=False),
    sa.Column('vitamin_b12_mcg', sa.Float(), nullable=False),
    sa.Column('vitamin_c_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_d_mcg', sa.Float(), nullable=False),
    sa.Column('vitamin_e_mg', sa.Float(), nullable=False),
    sa.Column('vitamin_k_mcg', sa.Float(), nullable=False),
    sa.Column('calcium_mg', sa.Float(), nullable=False),
    sa.Column('iron_mg', sa.Float(), nullable=False),
    sa.Column('magnesium_mg', sa.Float(), nullable=False),
    sa.Column('phosphorus_mg', sa.Float(), nullable=False),
    sa.Column('potassium_mg', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('zinc_mg', sa.Float(), nullable=False),
    sa.Column('copper_mg', sa.Float(), nullable=False),
    sa.Column('manganese_mg', sa.Float(), nullable=False),
    sa.Column('selenium_mcg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_nutrient_profiles_name'), 'food_nutrient_profiles', ['name'], unique=True)
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('consumed_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_nutrient_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('food_logs')
    op.drop_index(op.f('ix_food_nutrient_profiles_name'), table_name='food_nutrient_profiles')
    op.drop_table('food_nutrient_profiles')
    # ### end Alembic commands ###
