"""add wellness tables

Revision ID: b2c3d4e5f601
Revises: 1a8132f82266
Create Date: 2026-07-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f601"
down_revision: Union[str, None] = "1a8132f82266"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mood_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("mood", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_mood_entries_user_date"),
    )
    op.create_index(
        "ix_mood_entries_user_id_date", "mood_entries", ["user_id", "date"], unique=False
    )

    op.create_table(
        "water_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("glasses", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("goal", sa.Integer(), nullable=False, server_default="8"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_water_logs_user_date"),
    )
    op.create_index(
        "ix_water_logs_user_id_date", "water_logs", ["user_id", "date"], unique=False
    )

    op.create_table(
        "sleep_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("hours", sa.Numeric(4, 2), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=True),
        sa.Column("bedtime", sa.String(length=5), nullable=True),
        sa.Column("wake_time", sa.String(length=5), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_sleep_entries_user_date"),
    )
    op.create_index(
        "ix_sleep_entries_user_id_date", "sleep_entries", ["user_id", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sleep_entries_user_id_date", table_name="sleep_entries")
    op.drop_table("sleep_entries")

    op.drop_index("ix_water_logs_user_id_date", table_name="water_logs")
    op.drop_table("water_logs")

    op.drop_index("ix_mood_entries_user_id_date", table_name="mood_entries")
    op.drop_table("mood_entries")
    # ### end Alembic commands ###
