#!/usr/bin/env python3
"""Turn a BudgetBox SQLite snapshot into an archive a stranger could read.

The point of this script is the year 2036. By then this repo may not build,
Flutter may have moved on twice, and the API may be gone — but a folder of
CSVs, one JSON file and a plain-English README will still open. So every
nightly backup carries three redundant representations of the same facts:

    budgetbox.db        the SQLite file itself, still the best long-term
                        container there is (self-describing, single file,
                        readable by every language and most spreadsheets)
    tables/*.csv        one file per table, openable in Excel or Numbers
    budgetbox.json      the whole book in one structured document
    README.txt          what the columns mean, especially `*_paise`

It depends on nothing but the Python standard library, on purpose: a restore
must never require a working `uv sync`.
"""

from __future__ import annotations

import csv
import json
import sqlite3
import sys
from datetime import UTC, datetime
from pathlib import Path

# Money is stored as integer paise everywhere. Anyone reading this in a decade
# needs to be told that once, loudly, or every figure is 100x wrong.
README = """BudgetBox archive — {stamp}

WHAT THIS IS
  A complete copy of a personal finance ledger, written three ways so that at
  least one of them still opens whenever you are reading this.

    budgetbox.db     SQLite database. Open with: sqlite3 budgetbox.db
                     or any SQLite browser, or Python's built-in sqlite3.
    tables/*.csv     One file per table. Opens in Excel, Numbers, pandas.
    budgetbox.json   Everything in one JSON document.

  All three contain the same data. Trust budgetbox.db if they ever disagree.

READING THE NUMBERS
  * Every column ending in `_paise` is an INTEGER in paise (1/100 of a rupee).
    Divide by 100 for rupees. 250000 means Rs 2,500.00 — not Rs 250,000.
    It is stored this way so no rounding error can ever accumulate.
  * Dates written `YYYY-MM-DD` are calendar days in India Standard Time
    (UTC+5:30). Timestamps ending in `Z` are UTC instants.
  * `type` on a transaction is one of: expense, income, transfer.
  * Balances are NOT stored. An account's balance is the latest confirmed
    anchor (see the anchors table) plus every signed transaction after it.
    This is deliberate: it makes drift structurally impossible.
  * Rows in `vault_items` are encrypted blobs. The key never left the phone,
    so these are unreadable here by design. Everything else is plain.

TABLES
{tables}

Generated by bbx-archive.py. No BudgetBox code is needed to read any of this.
"""


def dump(db_path: Path, out_dir: Path) -> None:
    if not db_path.exists():
        raise SystemExit(f"no such database: {db_path}")

    out_dir.mkdir(parents=True, exist_ok=True)
    tables_dir = out_dir / "tables"
    tables_dir.mkdir(exist_ok=True)

    # Read-only, so this is safe against a live database even without the
    # VACUUM INTO snapshot in front of it.
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        names = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
        ]

        book: dict[str, list[dict[str, object]]] = {}
        summary: list[str] = []

        for table in names:
            rows = [dict(r) for r in conn.execute(f'SELECT * FROM "{table}"')]
            book[table] = rows
            summary.append(f"  {table:<24} {len(rows):>7} rows")

            columns = (
                list(rows[0].keys())
                if rows
                else [c[1] for c in conn.execute(f'PRAGMA table_info("{table}")')]
            )
            with (tables_dir / f"{table}.csv").open("w", newline="", encoding="utf-8") as fh:
                writer = csv.DictWriter(fh, fieldnames=columns)
                writer.writeheader()
                writer.writerows(rows)

        (out_dir / "budgetbox.json").write_text(
            json.dumps(book, indent=1, ensure_ascii=False, default=str),
            encoding="utf-8",
        )
        (out_dir / "README.txt").write_text(
            README.format(
                stamp=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
                tables="\n".join(summary),
            ),
            encoding="utf-8",
        )
        print(f"archived {len(names)} tables to {out_dir}")
    finally:
        conn.close()


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: bbx-archive.py <budgetbox.db> <out-dir>")
    dump(Path(sys.argv[1]), Path(sys.argv[2]))
